mu=c(69,166)
sigma=matrix(c(9,45,45,400),2,2)
bivariate_norm_rand_var<-mvrnorm(n=100, mu, sigma)
tail(bivariate_norm_rand_var)
summary(bivariate_norm_rand_var)
barplot(bivariate_norm_rand_var[,1], main="Bar plot of height in inches", xlab="Height in inches", col="red") 
barplot(bivariate_norm_rand_var[,2], main="Bar plot of weight in pounds", xlab="Weight in pounds", col="blue") 
boxplot(bivariate_norm_rand_var[,1], main="Box plot of height in inches", xlab="Height in inches", col="red") 
boxplot(bivariate_norm_rand_var[,2], main="Box plot of weight in pounds", xlab="Weight in pounds", col="blue") 
plot(bivariate_norm_rand_var, main="Scatter plot of height vs weight", xlab="Height in inches", ylab="Weight in pounds")
